// Rebuilds src/overlay.html from the web demo (../hydration-buddy.html), so any change to the
// buddy's look or animations there shows up in the desktop app. Run: npm run sync-buddy
const fs = require('fs');
const path = require('path');

const demo = process.argv[2] || path.join(__dirname, '..', '..', 'hydration-buddy.html');
const src = fs.readFileSync(demo, 'utf8');
const startCss = src.indexOf('/* =====================================================================\n   HYDRATION BUDDY COMPONENT');
const endCss = src.indexOf('/* ============================ END COMPONENT');
const startFacing = src.indexOf('<div class="hb-facing">');
const endFacing = src.lastIndexOf('</svg></div>', src.indexOf('<script')) + '</svg></div>'.length;
if ([startCss, endCss, startFacing].includes(-1) || endFacing < startFacing) {
  throw new Error(`Couldn't find the buddy component markers in ${demo}`);
}
// Optional extras (the "!!" shout marks) sit inside the walker, before the bubble.
const walkerStart = src.indexOf('<div class="hb-walker"');
const bubbleStart = src.indexOf('<div class="hb-bubble"', walkerStart);
const shouts = (src.slice(walkerStart, bubbleStart).match(/<span class="hb-shout[^]*?<\/span>/g) || []).join('');
// The HydrationBuddy controller class is shared too, so behaviour changes carry over.
const classStart = src.indexOf('class HydrationBuddy');
const classEnd = src.indexOf('\n}\n', classStart) + 3;
if (classStart === -1 || classEnd < classStart) throw new Error('HydrationBuddy class not found');
fs.writeFileSync(path.join(__dirname, '..', 'src', 'buddy-controller.js'),
  `// Generated by scripts/sync-buddy.js from hydration-buddy.html. Don't edit by hand.\n${src.slice(classStart, classEnd)}`);

const template = fs.readFileSync(path.join(__dirname, '..', 'src', 'overlay.template.html'), 'utf8');
const out = template
  .replace('{{COMPONENT_CSS}}', () => src.slice(startCss, endCss))
  .replace('{{SHOUTS}}', () => shouts)
  .replace('{{FACING}}', () => src.slice(startFacing, endFacing) + '\n        </div>');
fs.writeFileSync(path.join(__dirname, '..', 'src', 'overlay.html'), out);
console.log(`overlay.html rebuilt from ${demo}`);
